// Design 063 § Pinned contracts E: one beat per drawer, every param defaulted. It exceeds
// the tongue cost rule on purpose (validateSpec returns exactly that error), so it is a
// recording fixture, not a shipped move: `rec-move.mjs MOVE=kitchen-sink` plays it so every
// drawer is seen once on both seats. The first twelve beats alone are a valid spec.

export const kitchenSink = Object.freeze({
  id: 'kitchen-sink',
  name: 'Kitchen Sink',
  vgType: 'fire',
  statClass: 'special',
  tier: 3,
  family: 'burst',
  material: 'fire',
  durationMs: 2200,
  contactMs: 1100,
  pad: 1.7,
  attacker: { motion: 'rear-lurch', params: {} },
  defender: { motion: 'knock', params: {} },
  beats: [
    { at: 0, until: 700, layer: 'back', drawer: 'orbitCharge', params: { half: 'back' } },
    { at: 0, until: 700, layer: 'front', drawer: 'orbitCharge', params: { half: 'front' } },
    { at: 0, until: 700, layer: 'front', drawer: 'coreCharge', params: {} },
    { at: 640, until: 1000, layer: 'back', drawer: 'shockRings', params: {} },
    { at: 0, until: 700, layer: 'back', drawer: 'aura', params: {} },
    { at: 700, until: 1100, layer: 'front', drawer: 'beam', params: { kind: 'solid' } },
    { at: 700, until: 1100, layer: 'front', drawer: 'projectile', params: {} },
    { at: 700, until: 1100, layer: 'front', drawer: 'volley', params: {} },
    { at: 900, until: 1100, layer: 'front', drawer: 'bolt', params: { from: 'attacker' } },
    { at: 900, until: 2000, layer: 'back', drawer: 'vignette', params: {} },
    { at: 1100, until: 1850, layer: 'front', drawer: 'starFlare', params: {} },
    { at: 1100, until: 1280, layer: 'top', drawer: 'impactFlash', params: {} },
    { at: 1100, until: 1700, layer: 'back', drawer: 'terrain', params: { kind: 'crack' } },
    { at: 1100, until: 1500, layer: 'back', drawer: 'ring', params: { kind: 'floor' } },
    { at: 1100, until: 1400, layer: 'back', drawer: 'speedRays', params: {} },
    { at: 1100, until: 1600, layer: 'back', drawer: 'shards', params: {} },
    { at: 1100, until: 1600, layer: 'back', drawer: 'splash', params: {} },
    { at: 1100, until: 1300, layer: 'back', drawer: 'slashArc', params: {} },
    { at: 1100, until: 1700, layer: 'back', drawer: 'pillar', params: {} },
    { at: 1100, until: 1700, layer: 'back', drawer: 'spiral', params: {} },
    { at: 1100, until: 1600, layer: 'back', drawer: 'rain', params: {} },
    { at: 1100, until: 1600, layer: 'back', drawer: 'glyph', params: {} },
    { at: 1300, until: 2100, layer: 'back', drawer: 'cloud', params: {} },
    { at: 1400, until: 2200, layer: 'front', drawer: 'smoke', params: {} },
  ],
  particles: [
    {
      at: 1100,
      anchor: 'defender',
      count: 20,
      distance: 1.3,
      direction: -90,
      spread: 300,
      size: [0.05, 0.13],
      aspect: 0.3,
      gravity: 0.6,
      maxDelay: 0.12,
      durationMs: 760,
      kind: 'ember',
    },
  ],
  grain: 0.28,
});
