// Perfect Order Build & Battle Box — Bulbapedia "Perfect Order Build & Battle Box (TCG)", revision 4531476 (read 2026-09-28).
export default {
  key: 'perfect-order',
  source: { url: 'https://bulbapedia.bulbagarden.net/wiki/Perfect_Order_Build_%26_Battle_Box_(TCG)', revision: 4531476 },
  decks: {
    serperior: [
      '1 Serperior MEP 64',
      '2 Serperior POR 6',
      '3 Servine POR 5',
      '4 Snivy POR 4',
      '4 Shaymin POR 3',
      '2 Dawn PFL 87',
      '2 Drayton SSP 174',
      "2 Lillie's Determination MEG 119",
      '1 Lacey SCR 139',
      "1 Lana's Aid TWM 155",
      "1 Rosa's Encouragement POR 84",
      '1 Surfer ASC 200',
      '2 Bug Catching Set TWM 143',
      '2 Buddy-Buddy Poffin TEF 144',
      '2 Ultra Ball MEG 131',
      '2 Forest of Vitality MEG 117',
      '2 Growing Grass Energy POR 86', // Bulbapedia: "Growing G Energy"
      '6 Basic Grass Energy',
    ],
    barbaracle: [
      '1 Barbaracle MEP 65',
      '2 Barbaracle POR 43',
      '3 Binacle POR 42',
      '3 Landorus POR 41',
      '1 Hawlucha POR 46',
      '2 Drayton SSP 174',
      '2 Hilda WHT 84',
      "2 Lillie's Determination MEG 119",
      "1 Colress's Tenacity SFA 57",
      '1 Lacey SCR 139',
      '1 Surfer ASC 200',
      '1 Tarragon POR 85',
      '3 Fighting Gong MEG 116',
      '2 Poké Pad POR 81',
      '1 Enhanced Hammer TWM 148',
      '1 Premium Power Pro MEG 124',
      '2 Gravity Mountain SSP 177',
      '2 Rocky Fighting Energy POR 87', // Bulbapedia: "Rocky F Energy"
      '9 Basic Fighting Energy',
    ],
    tyrantrum: [
      '1 Tyrantrum MEP 66',
      '2 Tyrantrum POR 45',
      '3 Tyrunt POR 44',
      '3 Hawlucha POR 46',
      '4 Drayton SSP 174',
      "4 Team Rocket's Petrel DRI 176",
      "2 Lillie's Determination MEG 119",
      '4 Antique Jaw Fossil POR 68',
      '4 Poké Pad POR 81',
      "2 Team Rocket's Factory DRI 173",
      '4 Rocky Fighting Energy POR 87', // Bulbapedia: "Rocky F Energy"
      '2 Mist Energy TEF 161',
      '5 Basic Fighting Energy',
    ],
    doublade: [
      '1 Doublade MEP 67',
      '2 Aegislash POR 58',
      '3 Doublade POR 57',
      '4 Honedge POR 56',
      '2 Klefki POR 59',
      '2 Dawn PFL 87',
      '2 Hilda WHT 84',
      "2 Lillie's Determination MEG 119",
      "1 Colress's Tenacity SFA 57",
      '1 Lacey SCR 139',
      "1 Lana's Aid TWM 155",
      '1 Waitress ASC 215',
      '2 Buddy-Buddy Poffin TEF 144',
      '2 Poké Pad POR 81',
      '1 Enhanced Hammer TWM 148',
      '2 Full Metal Lab TEF 148',
      '4 Ignition Energy WHT 86',
      '7 Basic Metal Energy',
    ],
  },
};
