// Pitch Black Build & Battle Box — Bulbapedia "Pitch Black Build & Battle Box (TCG)", revision 4589383 (read 2026-09-28).
export default {
  key: 'pitch-black',
  source: { url: 'https://bulbapedia.bulbagarden.net/wiki/Pitch_Black_Build_%26_Battle_Box_(TCG)', revision: 4589383 },
  decks: {
    miraidon: [
      '1 Miraidon MEP 82',
      '3 Miraidon PBL 28',
      '3 Vikavolt PBL 26',
      '3 Charjabug PBL 25',
      '4 Grubbin PBL 2',
      "2 Brock's Scouting JTG 146",
      "1 Emcee's Hype DRI 163",
      '4 Hilda WHT 84',
      "2 Lillie's Determination MEG 119",
      '2 Poké Pad POR 81',
      '2 Rare Candy MEG 125',
      '2 Ultra Ball MEG 131',
      '4 Voltaic Lightning Energy PBL 84', // Bulbapedia: "Voltaic L Energy"
      '7 Basic Lightning Energy',
    ],
    slowbro: [
      '1 Slowbro MEP 83',
      '3 Slowbro PBL 30',
      '4 Slowpoke PBL 29',
      '2 Silvally PBL 70',
      '2 Type: Null PBL 69',
      "1 AZ's Tranquility CRI 76",
      "2 Brock's Scouting JTG 146",
      '3 Hilda WHT 84',
      "1 Lillie's Determination MEG 119",
      "2 Team Rocket's Petrel DRI 176",
      '2 Energy Search POR 72',
      '1 Energy Recycler DRI 164',
      '2 Poké Pad POR 81',
      '4 Ultra Ball MEG 131',
      '1 Air Balloon BLK 79',
      '2 Prism Tower CRI 80',
      '2 Ignition Energy WHT 86',
      '2 Telepathic Psychic Energy POR 88', // Bulbapedia: "Telepathic P Energy"
      '3 Basic Psychic Energy',
    ],
    dhelmise: [
      '1 Dhelmise MEP 84',
      '1 Spiritomb PBL 35',
      '4 Banette PBL 34',
      '4 Shuppet PBL 33',
      '4 Sinistcha PBL 6',
      '4 Poltchageist PBL 5',
      '3 Gwynn PBL 78',
      '2 Hilda WHT 84',
      "4 Iris's Fighting Spirit JTG 149",
      '4 Ultra Ball MEG 131',
      '2 Telepathic Psychic Energy POR 88', // Bulbapedia: "Telepathic P Energy"
      '7 Basic Psychic Energy',
    ],
    bastiodon: [
      '1 Bastiodon MEP 85',
      '2 Bastiodon PBL 62',
      '2 Shieldon PBL 61',
      '4 Skarmory PBL 60',
      "1 Emcee's Hype DRI 163",
      '1 Hilda WHT 84',
      "3 Lillie's Determination MEG 119",
      '2 Philippe CRI 79',
      "2 Team Rocket's Petrel DRI 176",
      '4 Antique Armor Fossil PBL 72',
      '1 Energy Search POR 72',
      '2 Poké Pad POR 81',
      '2 Rare Candy MEG 125',
      '3 Fossil Quarry PBL 76',
      '2 Magnetic Metal Energy CRI 85', // Bulbapedia: "Magnetic M Energy"
      '8 Basic Metal Energy',
    ],
  },
};
