import { chromium } from 'playwright';
import { renameSync } from 'node:fs';
const FROM = 'https://images.pokemontcg.io/sv3pt5/4_hires.png';
const TO = 'https://images.pokemontcg.io/sv3pt5/5_hires.png';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 720 }, recordVideo: { dir: '.agent/scratch/vid', size: { width: 1280, height: 720 } } });
const page = await ctx.newPage();
await page.route('https://static.cloudflareinsights.com/**', (r) => r.abort());
page.on('pageerror', (e) => console.log('pageerror', e.message));
await page.goto('http://localhost:4100/?e2e=1');
await page.waitForFunction(() => window.__ptcg?.ready === true, null, { timeout: 30000 });
await page.waitForTimeout(800);
await page.evaluate(async ([from, to]) => {
  const { visualRectOf } = await import('/src/setup/image-logic/iframe-rect.mjs');
  const { playEvolveScene } = await import('/src/setup/netcode/mat-fx/evolve-scene.js');
  const zone = visualRectOf(document.getElementById('selfContainer').contentDocument.getElementById('active'));
  const h = Math.min(zone.height * 0.9, 150), w = h * 0.716;
  const rect = { left: zone.left + (zone.width - w) / 2, top: zone.top + (zone.height - h) / 2, width: w, height: h };
  const img = document.createElement('img');
  img.src = from;
  Object.assign(img.style, { position: 'fixed', left: rect.left + 'px', top: rect.top + 'px', width: w + 'px', height: h + 'px', zIndex: 2400, borderRadius: '4px' });
  document.body.appendChild(img);
  await Promise.all([img.decode(), new Image().decode.call(Object.assign(new Image(), { src: to }))]);
  window.__go = () => { playEvolveScene({ rect, fromSrc: from, toSrc: to }); setTimeout(() => (img.src = to), 2048); };
}, [FROM, TO]);
await page.waitForTimeout(700);
await page.evaluate(() => window.__go());
await page.waitForTimeout(4300);
const v = page.video();
await ctx.close();
renameSync(await v.path(), 'out/evolve-active.webm');
await browser.close();
console.log('ok');
