// Design 065 § Data: the 81 signature moves of legendary/mythical/Paradox-legend Pokémon,
// the pinned species/form slug → signature table, and the material rules of § Options 4.
// Pure and frozen; generated from the design's signature list (one row per move, in its order).

/** id → { name, vgType, statClass: 'physical'|'special'|'status', power (null = none), owners, material } */
export const SIGNATURE_MOVES = Object.freeze({
  'crush-grip': {
    name: 'Crush Grip',
    vgType: 'normal',
    statClass: 'physical',
    power: null,
    owners: ['regigigas'],
    material: 'normal',
  },
  judgment: {
    name: 'Judgment',
    vgType: 'normal',
    statClass: 'special',
    power: 100,
    owners: ['arceus'],
    material: 'normal',
  },
  'multi-attack': {
    name: 'Multi-Attack',
    vgType: 'normal',
    statClass: 'physical',
    power: 120,
    owners: ['silvally'],
    material: 'normal',
  },
  'relic-song': {
    name: 'Relic Song',
    vgType: 'normal',
    statClass: 'special',
    power: 75,
    owners: ['meloetta'],
    material: 'normal',
  },
  'techno-blast': {
    name: 'Techno Blast',
    vgType: 'normal',
    statClass: 'special',
    power: 120,
    owners: ['genesect'],
    material: 'normal',
  },
  'tera-starstorm': {
    name: 'Tera Starstorm',
    vgType: 'normal',
    statClass: 'special',
    power: 120,
    owners: ['terapagos'],
    material: 'stellar',
  },
  'blue-flare': {
    name: 'Blue Flare',
    vgType: 'fire',
    statClass: 'special',
    power: 130,
    owners: ['reshiram'],
    material: 'fire',
  },
  'fusion-flare': {
    name: 'Fusion Flare',
    vgType: 'fire',
    statClass: 'special',
    power: 100,
    owners: ['kyurem', 'reshiram'],
    material: 'fire',
  },
  'magma-storm': {
    name: 'Magma Storm',
    vgType: 'fire',
    statClass: 'special',
    power: 100,
    owners: ['heatran'],
    material: 'fire',
  },
  'sacred-fire': {
    name: 'Sacred Fire',
    vgType: 'fire',
    statClass: 'physical',
    power: 100,
    owners: ['ho-oh'],
    material: 'fire',
  },
  'searing-shot': {
    name: 'Searing Shot',
    vgType: 'fire',
    statClass: 'special',
    power: 100,
    owners: ['victini'],
    material: 'fire',
  },
  'v-create': {
    name: 'V-create',
    vgType: 'fire',
    statClass: 'physical',
    power: 180,
    owners: ['victini'],
    material: 'fire',
  },
  'hydro-steam': {
    name: 'Hydro Steam',
    vgType: 'water',
    statClass: 'special',
    power: 80,
    owners: ['walking-wake'],
    material: 'water',
  },
  'origin-pulse': {
    name: 'Origin Pulse',
    vgType: 'water',
    statClass: 'special',
    power: 110,
    owners: ['kyogre'],
    material: 'water',
  },
  'steam-eruption': {
    name: 'Steam Eruption',
    vgType: 'water',
    statClass: 'special',
    power: 110,
    owners: ['volcanion'],
    material: 'water',
  },
  'surging-strikes': {
    name: 'Surging Strikes',
    vgType: 'water',
    statClass: 'physical',
    power: 25,
    owners: ['urshifu'],
    material: 'water',
  },
  'ivy-cudgel': {
    name: 'Ivy Cudgel',
    vgType: 'grass',
    statClass: 'physical',
    power: 100,
    owners: ['ogerpon'],
    material: 'grass',
  },
  'seed-flare': {
    name: 'Seed Flare',
    vgType: 'grass',
    statClass: 'special',
    power: 120,
    owners: ['shaymin'],
    material: 'grass',
  },
  'bolt-strike': {
    name: 'Bolt Strike',
    vgType: 'electric',
    statClass: 'physical',
    power: 130,
    owners: ['zekrom'],
    material: 'electric',
  },
  'electro-drift': {
    name: 'Electro Drift',
    vgType: 'electric',
    statClass: 'special',
    power: 100,
    owners: ['miraidon'],
    material: 'electric',
  },
  'fusion-bolt': {
    name: 'Fusion Bolt',
    vgType: 'electric',
    statClass: 'physical',
    power: 100,
    owners: ['kyurem', 'zekrom'],
    material: 'electric',
  },
  'plasma-fists': {
    name: 'Plasma Fists',
    vgType: 'electric',
    statClass: 'physical',
    power: 100,
    owners: ['zeraora'],
    material: 'electric',
  },
  'thunder-cage': {
    name: 'Thunder Cage',
    vgType: 'electric',
    statClass: 'special',
    power: 80,
    owners: ['regieleki'],
    material: 'electric',
  },
  thunderclap: {
    name: 'Thunderclap',
    vgType: 'electric',
    statClass: 'special',
    power: 70,
    owners: ['raging-bolt'],
    material: 'electric',
  },
  'wildbolt-storm': {
    name: 'Wildbolt Storm',
    vgType: 'electric',
    statClass: 'special',
    power: 100,
    owners: ['thundurus'],
    material: 'electric',
  },
  'freeze-shock': {
    name: 'Freeze Shock',
    vgType: 'ice',
    statClass: 'physical',
    power: 140,
    owners: ['kyurem'],
    material: 'ice',
  },
  'glacial-lance': {
    name: 'Glacial Lance',
    vgType: 'ice',
    statClass: 'physical',
    power: 120,
    owners: ['calyrex'],
    material: 'ice',
  },
  glaciate: {
    name: 'Glaciate',
    vgType: 'ice',
    statClass: 'special',
    power: 65,
    owners: ['kyurem'],
    material: 'ice',
  },
  'ice-burn': {
    name: 'Ice Burn',
    vgType: 'ice',
    statClass: 'special',
    power: 140,
    owners: ['kyurem'],
    material: 'ice',
  },
  'collision-course': {
    name: 'Collision Course',
    vgType: 'fighting',
    statClass: 'physical',
    power: 100,
    owners: ['koraidon'],
    material: 'fighting',
  },
  'sacred-sword': {
    name: 'Sacred Sword',
    vgType: 'fighting',
    statClass: 'physical',
    power: 90,
    owners: ['cobalion', 'terrakion', 'virizion', 'keldeo'],
    material: 'fighting',
  },
  'secret-sword': {
    name: 'Secret Sword',
    vgType: 'fighting',
    statClass: 'special',
    power: 85,
    owners: ['keldeo'],
    material: 'fighting',
  },
  'thunderous-kick': {
    name: 'Thunderous Kick',
    vgType: 'fighting',
    statClass: 'physical',
    power: 90,
    owners: ['zapdos'],
    material: 'fighting',
  },
  'malignant-chain': {
    name: 'Malignant Chain',
    vgType: 'poison',
    statClass: 'special',
    power: 100,
    owners: ['pecharunt'],
    material: 'poison',
  },
  'lands-wrath': {
    name: 'Land’s Wrath',
    vgType: 'ground',
    statClass: 'physical',
    power: 90,
    owners: ['zygarde'],
    material: 'ground',
  },
  'precipice-blades': {
    name: 'Precipice Blades',
    vgType: 'ground',
    statClass: 'physical',
    power: 120,
    owners: ['groudon'],
    material: 'ground',
  },
  'sandsear-storm': {
    name: 'Sandsear Storm',
    vgType: 'ground',
    statClass: 'special',
    power: 100,
    owners: ['landorus'],
    material: 'ground',
  },
  'thousand-arrows': {
    name: 'Thousand Arrows',
    vgType: 'ground',
    statClass: 'physical',
    power: 90,
    owners: ['zygarde'],
    material: 'ground',
  },
  'thousand-waves': {
    name: 'Thousand Waves',
    vgType: 'ground',
    statClass: 'physical',
    power: 90,
    owners: ['zygarde'],
    material: 'ground',
  },
  aeroblast: {
    name: 'Aeroblast',
    vgType: 'flying',
    statClass: 'special',
    power: 100,
    owners: ['lugia'],
    material: 'flying',
  },
  'bleakwind-storm': {
    name: 'Bleakwind Storm',
    vgType: 'flying',
    statClass: 'special',
    power: 100,
    owners: ['tornadus'],
    material: 'flying',
  },
  'dragon-ascent': {
    name: 'Dragon Ascent',
    vgType: 'flying',
    statClass: 'physical',
    power: 120,
    owners: ['rayquaza'],
    material: 'flying',
  },
  'oblivion-wing': {
    name: 'Oblivion Wing',
    vgType: 'flying',
    statClass: 'special',
    power: 80,
    owners: ['yveltal'],
    material: 'flying',
  },
  'freezing-glare': {
    name: 'Freezing Glare',
    vgType: 'psychic',
    statClass: 'special',
    power: 90,
    owners: ['articuno'],
    material: 'psychic',
  },
  'heart-swap': {
    name: 'Heart Swap',
    vgType: 'psychic',
    statClass: 'status',
    power: null,
    owners: ['manaphy'],
    material: 'psychic',
  },
  'hyperspace-hole': {
    name: 'Hyperspace Hole',
    vgType: 'psychic',
    statClass: 'special',
    power: 80,
    owners: ['hoopa'],
    material: 'psychic',
  },
  'luster-purge': {
    name: 'Luster Purge',
    vgType: 'psychic',
    statClass: 'special',
    power: 95,
    owners: ['latios'],
    material: 'psychic',
  },
  'mist-ball': {
    name: 'Mist Ball',
    vgType: 'psychic',
    statClass: 'special',
    power: 95,
    owners: ['latias'],
    material: 'psychic',
  },
  'mystical-power': {
    name: 'Mystical Power',
    vgType: 'psychic',
    statClass: 'special',
    power: 70,
    owners: ['azelf', 'mesprit', 'uxie'],
    material: 'psychic',
  },
  'photon-geyser': {
    name: 'Photon Geyser',
    vgType: 'psychic',
    statClass: 'special',
    power: 100,
    owners: ['necrozma'],
    material: 'psychic',
  },
  'prismatic-laser': {
    name: 'Prismatic Laser',
    vgType: 'psychic',
    statClass: 'special',
    power: 160,
    owners: ['necrozma'],
    material: 'psychic',
  },
  psyblade: {
    name: 'Psyblade',
    vgType: 'psychic',
    statClass: 'physical',
    power: 80,
    owners: ['iron-leaves'],
    material: 'psychic',
  },
  'psycho-boost': {
    name: 'Psycho Boost',
    vgType: 'psychic',
    statClass: 'special',
    power: 140,
    owners: ['deoxys'],
    material: 'psychic',
  },
  psystrike: {
    name: 'Psystrike',
    vgType: 'psychic',
    statClass: 'special',
    power: 100,
    owners: ['mewtwo'],
    material: 'psychic',
  },
  'diamond-storm': {
    name: 'Diamond Storm',
    vgType: 'rock',
    statClass: 'physical',
    power: 100,
    owners: ['diancie'],
    material: 'rock',
  },
  'mighty-cleave': {
    name: 'Mighty Cleave',
    vgType: 'rock',
    statClass: 'physical',
    power: 95,
    owners: ['iron-boulder'],
    material: 'rock',
  },
  'astral-barrage': {
    name: 'Astral Barrage',
    vgType: 'ghost',
    statClass: 'special',
    power: 120,
    owners: ['calyrex'],
    material: 'ghost',
  },
  'moongeist-beam': {
    name: 'Moongeist Beam',
    vgType: 'ghost',
    statClass: 'special',
    power: 100,
    owners: ['lunala'],
    material: 'ghost',
  },
  'shadow-force': {
    name: 'Shadow Force',
    vgType: 'ghost',
    statClass: 'physical',
    power: 120,
    owners: ['giratina'],
    material: 'ghost',
  },
  'spectral-thief': {
    name: 'Spectral Thief',
    vgType: 'ghost',
    statClass: 'physical',
    power: 90,
    owners: ['marshadow'],
    material: 'ghost',
  },
  'core-enforcer': {
    name: 'Core Enforcer',
    vgType: 'dragon',
    statClass: 'special',
    power: 100,
    owners: ['zygarde'],
    material: 'dragon',
  },
  'dragon-energy': {
    name: 'Dragon Energy',
    vgType: 'dragon',
    statClass: 'special',
    power: 150,
    owners: ['regidrago'],
    material: 'dragon',
  },
  'dynamax-cannon': {
    name: 'Dynamax Cannon',
    vgType: 'dragon',
    statClass: 'special',
    power: 100,
    owners: ['eternatus'],
    material: 'dragon',
  },
  eternabeam: {
    name: 'Eternabeam',
    vgType: 'dragon',
    statClass: 'special',
    power: 160,
    owners: ['eternatus'],
    material: 'dragon',
  },
  'nihil-light': {
    name: 'Nihil Light',
    vgType: 'dragon',
    statClass: 'special',
    power: 200,
    owners: ['zygarde'],
    material: 'dragon',
  },
  'roar-of-time': {
    name: 'Roar of Time',
    vgType: 'dragon',
    statClass: 'special',
    power: 150,
    owners: ['dialga'],
    material: 'dragon',
  },
  'spacial-rend': {
    name: 'Spacial Rend',
    vgType: 'dragon',
    statClass: 'special',
    power: 100,
    owners: ['palkia'],
    material: 'dragon',
  },
  'dark-void': {
    name: 'Dark Void',
    vgType: 'dark',
    statClass: 'status',
    power: null,
    owners: ['darkrai'],
    material: 'dark',
  },
  'fiery-wrath': {
    name: 'Fiery Wrath',
    vgType: 'dark',
    statClass: 'special',
    power: 90,
    owners: ['moltres'],
    material: 'dark',
  },
  'hyperspace-fury': {
    name: 'Hyperspace Fury',
    vgType: 'dark',
    statClass: 'physical',
    power: 100,
    owners: ['hoopa'],
    material: 'dark',
  },
  ruination: {
    name: 'Ruination',
    vgType: 'dark',
    statClass: 'special',
    power: 1,
    owners: ['chi-yu', 'chien-pao', 'ting-lu', 'wo-chien'],
    material: 'dark',
  },
  'wicked-blow': {
    name: 'Wicked Blow',
    vgType: 'dark',
    statClass: 'physical',
    power: 75,
    owners: ['urshifu'],
    material: 'dark',
  },
  'behemoth-bash': {
    name: 'Behemoth Bash',
    vgType: 'steel',
    statClass: 'physical',
    power: 100,
    owners: ['zamazenta'],
    material: 'steel',
  },
  'behemoth-blade': {
    name: 'Behemoth Blade',
    vgType: 'steel',
    statClass: 'physical',
    power: 100,
    owners: ['zacian'],
    material: 'steel',
  },
  'doom-desire': {
    name: 'Doom Desire',
    vgType: 'steel',
    statClass: 'special',
    power: 140,
    owners: ['jirachi'],
    material: 'steel',
  },
  'double-iron-bash': {
    name: 'Double Iron Bash',
    vgType: 'steel',
    statClass: 'physical',
    power: 60,
    owners: ['melmetal'],
    material: 'steel',
  },
  'sunsteel-strike': {
    name: 'Sunsteel Strike',
    vgType: 'steel',
    statClass: 'physical',
    power: 100,
    owners: ['solgaleo'],
    material: 'steel',
  },
  'tachyon-cutter': {
    name: 'Tachyon Cutter',
    vgType: 'steel',
    statClass: 'special',
    power: 50,
    owners: ['iron-crown'],
    material: 'steel',
  },
  'fleur-cannon': {
    name: 'Fleur Cannon',
    vgType: 'fairy',
    statClass: 'special',
    power: 130,
    owners: ['magearna'],
    material: 'fairy',
  },
  'natures-madness': {
    name: 'Nature’s Madness',
    vgType: 'fairy',
    statClass: 'special',
    power: null,
    owners: ['tapu-bulu', 'tapu-fini', 'tapu-koko', 'tapu-lele'],
    material: 'fairy',
  },
  'springtide-storm': {
    name: 'Springtide Storm',
    vgType: 'fairy',
    statClass: 'special',
    power: 100,
    owners: ['enamorus'],
    material: 'fairy',
  },
});
for (const move of Object.values(SIGNATURE_MOVES))
  Object.freeze(Object.freeze(move).owners);

/** Type-changing moves whose material follows the card's TCG type (§ Options 4). */
export const CARD_TYPED = Object.freeze(
  new Set(['judgment', 'multi-attack', 'techno-blast'])
);

/** normalizeEnergyType() result → material key. */
export const TCG_TO_MATERIAL = Object.freeze({
  grass: 'grass',
  fire: 'fire',
  water: 'water',
  lightning: 'electric',
  psychic: 'psychic',
  fighting: 'fighting',
  darkness: 'dark',
  metal: 'steel',
  dragon: 'dragon',
  fairy: 'fairy',
  colorless: 'normal',
});

/** Ogerpon's mask slug → Ivy Cudgel's material. */
export const MASK_MATERIAL = Object.freeze({
  ogerpon: 'grass',
  'ogerpon-wellspring-mask': 'water',
  'ogerpon-hearthflame-mask': 'fire',
  'ogerpon-cornerstone-mask': 'rock',
});

/** Species/form slug → signature move id; null = this form has no signature (stops the walk). */
export const SIGNATURE_BY_SLUG = Object.freeze({
  arceus: 'judgment',
  articuno: null,
  'articuno-galar': 'freezing-glare',
  azelf: 'mystical-power',
  calyrex: null,
  'calyrex-ice-rider': 'glacial-lance',
  'calyrex-shadow-rider': 'astral-barrage',
  'chi-yu': 'ruination',
  'chien-pao': 'ruination',
  cobalion: 'sacred-sword',
  darkrai: 'dark-void',
  deoxys: 'psycho-boost',
  dialga: 'roar-of-time',
  diancie: 'diamond-storm',
  enamorus: 'springtide-storm',
  eternatus: 'eternabeam',
  genesect: 'techno-blast',
  giratina: 'shadow-force',
  groudon: 'precipice-blades',
  heatran: 'magma-storm',
  'ho-oh': 'sacred-fire',
  hoopa: 'hyperspace-hole',
  'hoopa-unbound': 'hyperspace-fury',
  'iron-boulder': 'mighty-cleave',
  'iron-crown': 'tachyon-cutter',
  'iron-leaves': 'psyblade',
  jirachi: 'doom-desire',
  keldeo: 'secret-sword',
  koraidon: 'collision-course',
  kyogre: 'origin-pulse',
  kyurem: 'glaciate',
  'kyurem-black': 'freeze-shock',
  'kyurem-white': 'ice-burn',
  landorus: 'sandsear-storm',
  latias: 'mist-ball',
  latios: 'luster-purge',
  lugia: 'aeroblast',
  lunala: 'moongeist-beam',
  magearna: 'fleur-cannon',
  manaphy: 'heart-swap',
  marshadow: 'spectral-thief',
  melmetal: 'double-iron-bash',
  meloetta: 'relic-song',
  mesprit: 'mystical-power',
  mewtwo: 'psystrike',
  miraidon: 'electro-drift',
  moltres: null,
  'moltres-galar': 'fiery-wrath',
  necrozma: 'prismatic-laser',
  'necrozma-dawn': 'moongeist-beam',
  'necrozma-dusk': 'sunsteel-strike',
  'necrozma-ultra': 'photon-geyser',
  ogerpon: 'ivy-cudgel',
  palkia: 'spacial-rend',
  pecharunt: 'malignant-chain',
  'raging-bolt': 'thunderclap',
  rayquaza: 'dragon-ascent',
  regidrago: 'dragon-energy',
  regieleki: 'thunder-cage',
  regigigas: 'crush-grip',
  reshiram: 'blue-flare',
  shaymin: 'seed-flare',
  silvally: 'multi-attack',
  solgaleo: 'sunsteel-strike',
  'tapu-bulu': 'natures-madness',
  'tapu-fini': 'natures-madness',
  'tapu-koko': 'natures-madness',
  'tapu-lele': 'natures-madness',
  terapagos: 'tera-starstorm',
  terrakion: 'sacred-sword',
  thundurus: 'wildbolt-storm',
  'ting-lu': 'ruination',
  tornadus: 'bleakwind-storm',
  urshifu: 'wicked-blow',
  'urshifu-rapid-strike': 'surging-strikes',
  'urshifu-rapid-strike-gmax': 'surging-strikes',
  uxie: 'mystical-power',
  victini: 'v-create',
  virizion: 'sacred-sword',
  volcanion: 'steam-eruption',
  'walking-wake': 'hydro-steam',
  'wo-chien': 'ruination',
  yveltal: 'oblivion-wing',
  zacian: 'behemoth-blade',
  zamazenta: 'behemoth-bash',
  zapdos: null,
  'zapdos-galar': 'thunderous-kick',
  zekrom: 'bolt-strike',
  zeraora: 'plasma-fists',
  zygarde: 'lands-wrath',
  'zygarde-10': 'thousand-arrows',
  'zygarde-complete': 'core-enforcer',
  'zygarde-mega': 'nihil-light',
});
